// create an order constants
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

//get order details constants
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

//pay for an order constants
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

//update order to out for delivery constants
export const ORDER_OUT_FOR_DELIVERY_REQUEST = "ORDER_OUT_FOR_DELIVERY_REQUEST";
export const ORDER_OUT_FOR_DELIVERY_SUCCESS = "ORDER_OUT_FOR_DELIVERY_SUCCESS";
export const ORDER_OUT_FOR_DELIVERY_FAIL = "ORDER_OUT_FOR_DELIVERY_FAIL";
export const ORDER_OUT_FOR_DELIVERY_RESET = "ORDER_OUT_FOR_DELIVERY_RESET";

//update order to delivered constants
export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

//list my orders constants
export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

// list all orders
export const ORDER_LIST_ALL_REQUEST = "ORDER_LIST_ALL_REQUEST";
export const ORDER_LIST_ALL_SUCCESS = "ORDER_LIST_ALL_SUCCESS";
export const ORDER_LIST_ALL_FAIL = "ORDER_LIST_ALL_FAIL";

// verify a transaction
export const ORDER_VERIFY_TRANSACTION_REQUEST =
  "ORDER_VERIFY_TRANSACTION_REQUEST";
export const ORDER_VERIFY_TRANSACTION_SUCCESS =
  "ORDER_VERIFY_TRANSACTION_SUCCESS";
export const ORDER_VERIFY_TRANSACTION_FAIL = "ORDER_VERIFY_TRANSACTION_FAIL";
